name       : nitrogen
version    : 1.6.0
release    : 1
source     :
    - http://projects.l3ib.org/nitrogen/files/nitrogen-1.6.0.tar.gz : 194a423fa4d24db069a64d2ffa1e4ece2e65d2466aed9ee037a59f3d141634de
license    : GPL-2.0
component  : desktop.i3
summary    : Background browser and setter for X windows.
description: |
    Background browser and setter for X windows.
builddeps  :
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(atkmm-1.6)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
