name       : nitrogen
version    : 1.6.1
release    : 10
source     :
    - https://github.com/l3ib/nitrogen/archive/1.6.1.tar.gz : 12ad31c1e2c44f486b5ca7f7d48bc5b07fb92bf15977e1793624e9e64c38b9a7
license    : GPL-2.0-only
component  : desktop.i3
summary    : Background browser and setter for X windows.
description: |
    Background browser and setter for X windows.
builddeps  :
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(atkmm-1.6)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
