name       : nitrogen
version    : 1.5.2
release    : 1
source     :
    - http://projects.l3ib.org/nitrogen/files/nitrogen-1.5.2.tar.gz : 60a2437ce6a6c0ba44505fc8066c1973140d4bb48e1e5649f525c7b0b8bf9fd2
license    : GPL-2.0
component  : desktop.core
summary    : Background browser and setter for X windows.
description: |
    Background browser and setter for X windows.
builddeps  :
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(atkmm-1.6)
setup      : |
    %reconfigure
    %configure
build      : |
    %make
install    : |
    %make_install
